-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "3200x2000@60.00", position = "0x1088", scale = 2.00 })
hl.monitor({ output = "DP-2", mode = "1920x1200@60.00", position = "1600x1088", scale = 1.25 })
hl.monitor({ output = "DP-1", mode = "1920x1200@60.00", position = "-1536x1088", scale = 1.25 })
