-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-7", mode = "1920x1080@60.00", position = "-7040x0", scale = 1.00 })
hl.monitor({ output = "DP-5", mode = "1920x1080@60.00", position = "-5120x0", scale = 1.00 })
hl.monitor({ output = "DP-6", mode = "1920x1080@60.00", position = "-3200x0", scale = 1.00 })
