package main

import (
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func putGoFixture(t *testing.T, root, name, contents string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0644); err != nil {
		t.Fatal(err)
	}
}

func hasGoRule(r Report, id string) bool {
	for _, finding := range r.Findings {
		if finding.Kind == "rule" && finding.Rule == id {
			return true
		}
	}
	return false
}

func TestGoErosionFindsHighMassCulprit(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "main.go", `package main
func big(x int) bool {
 if x == 1 || x == 2 || x == 3 || x == 4 || x == 5 || x == 6 || x == 7 || x == 8 || x == 9 || x == 10 || x == 11 { return true }
 return false
}
func small() { println("hello") }
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	if r.HighCCFunctions != 1 || r.TotalFunctions != 2 || r.Erosion <= 0 || r.Erosion >= 1 {
		t.Fatalf("unexpected erosion: %+v", r)
	}
	found := false
	for _, f := range r.Findings {
		if f.Kind == "erosion" && f.CC == 12 && f.Mass > 0 && f.Line == 2 {
			found = true
		}
	}
	if !found {
		t.Fatalf("missing high-CC function: %+v", r.Findings)
	}
}

func TestGoVerbosityCombinesRuleAndClonesWithoutDoubleCounting(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "main.go", `package main
func a(v bool) bool {
 if v == true {
  return true
 } else {
  return false
 }
 x := 1
 x = x
 println("a")
 return v
}
func b(v bool) bool {
 if v == true {
  return true
 } else {
  return false
 }
 x := 1
 x = x
 println("a")
 return v
}
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	if !hasGoRule(r, "bool-comparison") || !hasGoRule(r, "boolean-return-if-else") || !hasGoRule(r, "self-assignment") {
		t.Fatalf("missing adapted rules: %+v", r.Findings)
	}
	if r.CloneLines == 0 || r.RuleLines == 0 || r.FlaggedLines > r.CloneLines+r.RuleLines || r.FlaggedLines == 0 {
		t.Fatalf("incorrect union: %+v", r)
	}
	if math.Abs(r.Verbosity-float64(r.FlaggedLines)/float64(r.SourceLines)) > 0.000001 {
		t.Fatalf("invalid verbosity: %+v", r)
	}
}

func TestGoScopeAndGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "src/owned.go", "package src\nfunc owned() {}\n")
	putGoFixture(t, dir, "other/other.go", "package other\nfunc other() {}\n")
	putGoFixture(t, dir, "src/view_templ.go", "package src\nfunc huge() {}\n")
	putGoFixture(t, dir, "src/view.templ", "templ View() { <div>Hello</div> }\n")
	putGoFixture(t, dir, "src/gen.go", "// Code generated by a tool. DO NOT EDIT.\npackage src\nfunc generated() {}\n")
	putGoFixture(t, dir, "src/owned_test.go", "package src\nfunc TestOwned() {}\n")
	r, err := analyzeGoProject(dir, "src", false)
	if err != nil {
		t.Fatal(err)
	}
	if r.FilesScanned != 1 || r.TotalFunctions != 1 || r.TemplFiles != 1 || r.Excluded["generated"] != 1 || r.Excluded["templ generated"] != 1 || r.Excluded["tests"] != 1 {
		t.Fatalf("incorrect scope: %+v", r)
	}
	withTests, err := analyzeGoProject(dir, "src", true)
	if err != nil || withTests.FilesScanned != 2 {
		t.Fatalf("tests not included: %+v, %v", withTests, err)
	}
	if _, err := analyzeGoProject(dir, "../", false); err == nil || !strings.Contains(err.Error(), "within project root") {
		t.Fatalf("expected scope rejection, got %v", err)
	}
}

func TestGoCloneScopeChangesWhenPeerFileIsExcluded(t *testing.T) {
	dir := t.TempDir()
	body := `package pkg
func use() {
 if true {
  println("repeat")
  println("shared")
 }
 println("done")
}
`
	putGoFixture(t, dir, "a/a.go", body)
	putGoFixture(t, dir, "b/b.go", body)
	whole, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	part, err := analyzeGoProject(dir, "a", false)
	if err != nil {
		t.Fatal(err)
	}
	if whole.CloneLines == 0 || part.CloneLines != 0 || whole.Verbosity <= part.Verbosity {
		t.Fatalf("expected cross-file clone only at root: whole %+v, part %+v", whole, part)
	}
}

func TestGoRulesAdaptManualMinAndBoolCast(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "metrics.go", `package demo
func pick(a, b int, ok bool) int {
 var m int
 if a > b {
  m = a
 } else {
  m = b
 }
 if bool(ok) { return m }
 return b
}
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	if !hasGoRule(r, "manual-min-max") || !hasGoRule(r, "pointless-bool-cast") {
		t.Fatalf("missing translated rules: %+v", r.Findings)
	}
}

func TestGoBroaderVerbosityPatterns(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "sample.go", `package demo
func expensive() bool { return true }
func f(a, b int, text string) (int, string) {
 if expensive() { return a + 0, text + "" }
 if a > b { return a, text }
 return b, text
}
func pick(a, b int) int {
 if a > b { return a }
 return b
}
func boolValue(x bool) bool {
 return x && true
}
func boolGuard() bool {
 if expensive() { return true }
 return false
}
func threeLines() {
 if true {
  println("same")
 }
 println("again")
}
func otherThreeLines() {
 if true {
  println("same")
 }
 println("again")
}
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	for _, rule := range []string{"numeric-identity", "empty-string-concat", "boolean-identity", "manual-min-max-return", "boolean-return-guard"} {
		if !hasGoRule(r, rule) {
			t.Errorf("missing broader rule %q", rule)
		}
	}
	if r.CloneLines == 0 {
		t.Fatal("expected three-SLOC duplicated block")
	}
}

func TestGoRulesAvoidRequiredIdioms(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "valid.go", `package demo
import "errors"
func f(x []int) error {
 if len(x) == 0 { return errors.New("empty") }
 if len(x) > 0 { return nil }
 for _, v := range x { if v == 1 { continue }; println(v) }
 return nil
}
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range r.Findings {
		if f.Kind == "rule" {
			t.Fatalf("unexpected Go idiom rule: %+v", f)
		}
	}
}

func TestGoRulesAdaptConditionalAndLoopPatterns(t *testing.T) {
	dir := t.TempDir()
	putGoFixture(t, dir, "sample.go", `package demo
func f(v bool) bool {
 if v { if !v { println("impossible") } }
 if v { return true }
 return false
}
func loop() {
 for i := 0; i < 3; i++ {
  if i == 1 { continue }
  if i == 2 { continue }
  println(i)
  continue
 }
}
`)
	r, err := analyzeGoProject(dir, ".", false)
	if err != nil {
		t.Fatal(err)
	}
	for _, rule := range []string{"nested-if-no-else", "boolean-return-guard", "repeated-if-continue", "redundant-continue"} {
		if !hasGoRule(r, rule) {
			t.Errorf("missing adapted %s: %+v", rule, r.Findings)
		}
	}
}
